# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The swapping algorithm for computing Wasserstein barycenters
#'
#' @name swap_rcpp
#'
#' @param samples A cube containing samples for all subset posteriors (rows =
#'   subsets, columns = par, slices = samples)
#' @param acc accuracy
#' @param iter maximum number of iterations of the algorithm
#'
#' @return a three dimensional array (rows = subsets, columns = par, slices =
#'   samples) containing output from the swapping algorithm.
#'
swap_rcpp <- function(samples, acc = 0.001, iter = 10L) {
    .Call(`_waspr_swap_rcpp`, samples, acc, iter)
}

#' Estimate the mode by finding the highest posterior density interval
#'
#' @param x a  sample from which to estimate the interval
#' @param cip bandwidth for the algorithm, ranging from 0 to 1
#'
#' @section Details:
#'   The bandwidth \code{cip} is set to 0.95 to find the 95% HPD interval and
#'   to 0.1 to compute the mode.
#'
#' @return a scalar containing the estimate of the mode
#'
hmode <- function(x, cip) {
    .Call(`_waspr_hmode`, x, cip)
}

#' Find the highest density interval.
#'
#' @param x a  sample from which to estimate the interval
#' @param cip bandwidth for the algorithm, ranging from 0 to 1
#'
#' @return a vector of length 2 containing the lower and upper bound of the HPD interval.
#'
#' The bandwidth \code{cip} is set to 0.95 to find the 95% HPD interval and to 0.1 to compute the mode.
#'
hmodeci <- function(x, cip) {
    .Call(`_waspr_hmodeci`, x, cip)
}

